schema_version = "1.0.0"

id = "notebookconnector"
version = "0.1.0"
name = "Notebook Connector"
tagline = "Use Blender as a kernel for running Jupyter Notebooks"
maintainer = "Brady Johnston<brady.johnston@me.com>"
type = "add-on"
website = "https://bradyajohnston.github.io/NotebookConnector"
platforms = [
	"macos-arm64",
]
tags = [
	"Geometry Nodes",
	"Import-Export"
]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later"
]
copyright =[
	"2022-2024 Brady Johnston",
]

wheels = [
	"./wheels/tinycss2-1.3.0-py3-none-any.whl",
	"./wheels/rfc3986_validator-0.1.1-py2.py3-none-any.whl",
	"./wheels/jedi-0.19.1-py2.py3-none-any.whl",
	"./wheels/appnope-0.1.4-py2.py3-none-any.whl",
	"./wheels/arrow-1.3.0-py3-none-any.whl",
	"./wheels/sniffio-1.3.1-py3-none-any.whl",
	"./wheels/certifi-2024.8.30-py3-none-any.whl",
	"./wheels/pexpect-4.9.0-py2.py3-none-any.whl",
	"./wheels/traitlets-5.14.3-py3-none-any.whl",
	"./wheels/PyYAML-6.0.2-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/parso-0.8.4-py2.py3-none-any.whl",
	"./wheels/pygments-2.18.0-py3-none-any.whl",
	"./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
	"./wheels/httpcore-1.0.5-py3-none-any.whl",
	"./wheels/tornado-6.4.1-cp38-abi3-macosx_10_9_arm64.whl",
	"./wheels/httpx-0.27.2-py3-none-any.whl",
	"./wheels/rpds_py-0.20.0-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/jupyterlab_pygments-0.3.0-py3-none-any.whl",
	"./wheels/babel-2.16.0-py3-none-any.whl",
	"./wheels/nbclient-0.10.0-py3-none-any.whl",
	"./wheels/ptyprocess-0.7.0-py2.py3-none-any.whl",
	"./wheels/pyzmq-26.2.0-cp311-cp311-macosx_10_15_arm64.whl",
	"./wheels/uri_template-1.3.0-py3-none-any.whl",
	"./wheels/jupyter_events-0.10.0-py3-none-any.whl",
	"./wheels/asttokens-2.4.1-py2.py3-none-any.whl",
	"./wheels/jupyter_lsp-2.2.5-py3-none-any.whl",
	"./wheels/soupsieve-2.6-py3-none-any.whl",
	"./wheels/pandocfilters-1.5.1-py2.py3-none-any.whl",
	"./wheels/jsonschema_specifications-2023.12.1-py3-none-any.whl",
	"./wheels/nbconvert-7.16.4-py3-none-any.whl",
	"./wheels/rfc3339_validator-0.1.4-py2.py3-none-any.whl",
	"./wheels/websocket_client-1.8.0-py3-none-any.whl",
	"./wheels/prometheus_client-0.21.0-py3-none-any.whl",
	"./wheels/jupyter_server_terminals-0.5.3-py3-none-any.whl",
	"./wheels/referencing-0.35.1-py3-none-any.whl",
	"./wheels/debugpy-1.8.5-cp311-cp311-macosx_12_0_arm64.whl",
	"./wheels/jinja2-3.1.4-py3-none-any.whl",
	"./wheels/mistune-3.0.2-py3-none-any.whl",
	"./wheels/beautifulsoup4-4.12.3-py3-none-any.whl",
	"./wheels/setuptools-75.1.0-py3-none-any.whl",
	"./wheels/notebook_shim-0.2.4-py3-none-any.whl",
	"./wheels/platformdirs-4.3.6-py3-none-any.whl",
	"./wheels/MarkupSafe-2.1.5-cp311-cp311-macosx_10_9_arm64.whl",
	"./wheels/prompt_toolkit-3.0.47-py3-none-any.whl",
	"./wheels/jupyterlab_server-2.27.3-py3-none-any.whl",
	"./wheels/argon2_cffi-23.1.0-py3-none-any.whl",
	"./wheels/psutil-6.0.0-cp38-abi3-macosx_11_0_arm64.whl",
	"./wheels/urllib3-2.2.3-py3-none-any.whl",
	"./wheels/json5-0.9.25-py3-none-any.whl",
	"./wheels/jupyter_server-2.14.2-py3-none-any.whl",
	"./wheels/pure_eval-0.2.3-py3-none-any.whl",
	"./wheels/stack_data-0.6.3-py3-none-any.whl",
	"./wheels/requests-2.32.3-py3-none-any.whl",
	"./wheels/Send2Trash-1.8.3-py3-none-any.whl",
	"./wheels/jsonschema-4.23.0-py3-none-any.whl",
	"./wheels/ipython-8.27.0-py3-none-any.whl",
	"./wheels/nest_asyncio-1.6.0-py3-none-any.whl",
	"./wheels/jupyter_client-8.6.3-py3-none-any.whl",
	"./wheels/matplotlib_inline-0.1.7-py3-none-any.whl",
	"./wheels/python_json_logger-2.0.7-py3-none-any.whl",
	"./wheels/decorator-5.1.1-py3-none-any.whl",
	"./wheels/h11-0.14.0-py3-none-any.whl",
	"./wheels/fqdn-1.5.1-py3-none-any.whl",
	"./wheels/defusedxml-0.7.1-py2.py3-none-any.whl",
	"./wheels/bleach-6.1.0-py3-none-any.whl",
	"./wheels/ipykernel-6.29.5-py3-none-any.whl",
	"./wheels/isoduration-20.11.0-py3-none-any.whl",
	"./wheels/pycparser-2.22-py3-none-any.whl",
	"./wheels/jupyterlab-4.2.5-py3-none-any.whl",
	"./wheels/jsonpointer-3.0.0-py2.py3-none-any.whl",
	"./wheels/terminado-0.18.1-py3-none-any.whl",
	"./wheels/overrides-7.7.0-py3-none-any.whl",
	"./wheels/idna-3.10-py3-none-any.whl",
	"./wheels/types_python_dateutil-2.9.0.20240906-py3-none-any.whl",
	"./wheels/webcolors-24.8.0-py3-none-any.whl",
	"./wheels/jupyter_core-5.7.2-py3-none-any.whl",
	"./wheels/nbformat-5.10.4-py3-none-any.whl",
	"./wheels/cffi-1.17.1-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/six-1.16.0-py2.py3-none-any.whl",
	"./wheels/packaging-24.1-py3-none-any.whl",
	"./wheels/executing-2.1.0-py2.py3-none-any.whl",
	"./wheels/typing_extensions-4.12.2-py3-none-any.whl",
	"./wheels/attrs-24.2.0-py3-none-any.whl",
	"./wheels/anyio-4.6.0-py3-none-any.whl",
	"./wheels/wcwidth-0.2.13-py2.py3-none-any.whl",
	"./wheels/comm-0.2.2-py3-none-any.whl",
	"./wheels/webencodings-0.5.1-py2.py3-none-any.whl",
	"./wheels/argon2_cffi_bindings-21.2.0-cp38-abi3-macosx_10_9_arm64.whl",
	"./wheels/async_lru-2.0.4-py3-none-any.whl",
	"./wheels/fastjsonschema-2.20.0-py3-none-any.whl",
	"./wheels/charset_normalizer-3.3.2-cp311-cp311-macosx_11_0_arm64.whl",
]

[permissions]
files = "Connecting and registering to nodebook backends"